sudo: false
language: generic

matrix:
  include:
    - env: CC=gcc-5
      addons:
        apt:
          packages: ['g++-5', 'ninja-build']
          sources: ubuntu-toolchain-r-test
    - env: CC=clang-3.8
      addons:
        apt:
          packages: ['clang-3.8', 'ninja-build']
          sources: ubuntu-toolchain-r-test

before_install:
  - export PATH="$HOME/bin:$PATH"
  - mkdir ~/bin
  - mkdir tools
  - wget --no-check-certificate --no-clobber -O tools/cmake https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.sh || true
  - chmod -R +x tools

install:
  - tools/cmake --prefix="$HOME" --exclude-subdir

before_script:
  - mkdir build
  - cd build

script:
  - cmake -G"Ninja" ..
  - ninja
